/// Flutter icons Icon_part2
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icon_part2
///      fonts:
///       - asset: fonts/Icon_part2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Icon_part2 {
  Icon_part2._();
  static const _kFontFam = 'Icon_part2';
  static const String? _kFontPkg = null;
  static const IconData settingicon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lamp = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon__photo_camera = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smart_irrigation = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon__setting = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
